import express from "express";
import fetch from "node-fetch";

const router = express.Router();

router.post("/create-payment", async (req, res) => {
  try {
    const response = await fetch("https://connect.squareupsandbox.com/v2/payments", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.SQUARE_ACCESS_TOKEN}`,
      },
      body: JSON.stringify({
        source_id: req.body.nonce, // generated by Square Web Payments SDK
        amount_money: {
          amount: 1000, // $10.00 (in cents)
          currency: "USD"
        },
        idempotency_key: crypto.randomUUID(),
      }),
    });

    const data = await response.json();
    res.json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
